### ISSUE TITLE
Cards can be stacked 🐛

### ISSUE THREAD

**Issue by chrisheninger** [chrisheninger/matchimals.fun#18]
Logic is allowing cards to be stacked if valid. 🙈

Update: While it doesn't appear to be adding points– it is leading to the turn being ended. Whether or not the card is removed from the player's deck or if the turn just ends will need to be debugged.

**Comment by danieldiaz14** [comment]
Hey there i'd be happy to help. Did you want to make it so they can't stack or that the points are updated?

**Comment by chrisheninger** [comment]
Hi @danieldiaz14– the correct behavior should be that you should *not* be able to stack the cards. You'll want to add some logic to `isLegalMove` to make sure that we `return false` in the case a card already exists in the clicked cell.

Thanks! Look forward to your PR, let me know if there's anything I can do to assist!

**Comment by chrisheninger** [comment]
Double checking the code– I would've expected `if (cells[id] === null) {` to handle this bug but something seems weird– you'll need to debug around there to figure out what's happening.

**Comment by danieldiaz14** [comment]
Awesome thanks for the tip! I believe I fixed it following what you mentioned above. Played the game and tested it, let me know if there is anything else I can help with :)

https://github.com/chrisheninger/matchimals.fun/pull/20

**Comment by chrisheninger** [comment]
Landed on https://matchimals.fun– looks like it's working! 👍
